# image will be published to ghcr.io/<user>/<name>
name: bee-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - mangohud
      - gamescope
      - bottles
      - distrobox
      - fastfetch
      - adw-gtk3-theme
      - gnome-extensions-app
      - steam
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: Flathub (system)
      install:
        - org.gnome.baobab
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Evince
        - org.gnome.Firmware
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.TextEditor
        - org.gnome.Weather
        - com.spotify.Client
        - io.bassi.Amberol
        - com.github.johnfactotum.Foliate
        - io.mpv.Mpv
        - org.prismlauncher.PrismLauncher
        - org.qbittorrent.qBittorrent
        - com.github.tchx84.Flatseal
        - md.obsidian.Obsidian
        - com.discordapp.Discord
      remove:
        
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - IntelOneMono
        - JetBrainsMono
        - SourceCodePro
        - NerdFontsSymbolsOnly
        - Terminus
      google-fonts:
        - Roboto
        - Open Sans
        - Inter
